-- Meridian Business Intelligence
-- Seed Data Loader
-- Run after schema.sql is executed successfully
-- Loads synthetic CSVs generated by data_generation.py

\COPY clients FROM '01_raw_data/clients.csv'
    WITH (FORMAT csv, HEADER true, DELIMITER ',');

\COPY portfolios FROM '01_raw_data/portfolios.csv'
    WITH (FORMAT csv, HEADER true, DELIMITER ',');

\COPY transactions FROM '01_raw_data/transactions.csv'
    WITH (FORMAT csv, HEADER true, DELIMITER ',');

-- Verify row counts after loading
SELECT
    'clients'       AS table_name,
    COUNT(*)        AS row_count
FROM clients

UNION ALL

SELECT
    'portfolios',
    COUNT(*)
FROM portfolios

UNION ALL

SELECT
    'transactions',
    COUNT(*)
FROM transactions;

-- Verify referential integrity
SELECT
    COUNT(*) AS portfolios_without_client
FROM portfolios p
LEFT JOIN clients c ON p.client_id = c.client_id
WHERE c.client_id IS NULL;

SELECT
    COUNT(*) AS transactions_without_portfolio
FROM transactions t
LEFT JOIN portfolios p ON t.portfolio_id = p.portfolio_id
WHERE p.portfolio_id IS NULL;